{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d41ed5b5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WELCOME TO CHILD NUTRITION CALCULATOR\n",
      "Name:Peter Parker\n",
      "Age:7\n",
      "Height(inches):45\n",
      "Weight(lb):60\n",
      "\n",
      "Calorie Consumption of child\n",
      "Milk:300\n",
      "Vegetables:300\n",
      "Meat:200\n",
      "Lentils:100\n",
      "Egg:300\n",
      "Rice:300\n",
      "\n",
      "BMI of Peter Parker is 20.83 and he (she) is Healthy.\n",
      "\n",
      "The daily calorie consumption of Peter Parker is 1800 and he (she) is taking 1809, he or she is nourished.\n"
     ]
    }
   ],
   "source": [
    "# bmiResult function to print the BMI Categories\n",
    "def bmiResult(childName,bmi):\n",
    "    if bmi<16:                        #if bmi<16-Severely Underweight\n",
    "        print(\"BMI of {0} is {1} and he (she) is Severely Underweight.\".format(childName,bmi))\n",
    "    elif bmi>=16 and bmi<18.5:        #if bmi>=16 and bmi<18.5- Underweight\n",
    "        print(\"BMI of {0} is {1} and he (she) is Underweight.\".format(childName,bmi))\n",
    "    elif bmi>=18.5 and bmi<25:        #if bmi>=18.5 and bmi<25-Healthy\n",
    "        print(\"BMI of {0} is {1} and he (she) is Healthy.\".format(childName,bmi))\n",
    "    elif bmi>=25 and bmi<30:          #if bmi>=25 and bmi<30-Overweight\n",
    "        print(\"BMI of {0} is {1} and he (she) is Overweight.\".format(childName,bmi))\n",
    "    elif bmi>=30:                     #if bmi>=30-Obese\n",
    "        print(\"BMI of {0} is {1} and he (she) is Obese.\".format(childName,bmi\n",
    "                                                            \n",
    "# Function bmiResult: This function takes a child's name and BMI as inputs, \n",
    "# and then prints out the BMI category based on predefined ranges. \n",
    "# It categorizes the child as \"Severely Underweight,\" \"Underweight,\" \"Healthy,\" \"Overweight,\" or \"Obese\" based on their BMI.\n",
    "                                                                \n",
    "# If the condition of the previous line is True (i.e., if the BMI is less than 16),\n",
    "# this line prints a formatted string using the .format() method. \n",
    "# It fills in the placeholders {0} and {1} with the values of childName and bmi, respectively.\n",
    "# This line informs the user that the child is severely underweight.\n",
    "\n",
    "\n",
    "# caloriesCalculator function to calculate the total calories consumed by child in a day\n",
    "def caloriesCalculator(calories):\n",
    "    caloriesCount={\"Milk\":100,\"Vegetables\":85,\"Meat\":143,\"Lentils\":113,\"Egg\":155,\"Rice\":130}\n",
    "    # dictionary that contains the calories contained in 100 gm of food they consumed\n",
    "    totalCalories = 0\n",
    "    for key, value in calories.items():\n",
    "            calorie=value                      # calorie- total number of calories consumed by child\n",
    "            while calorie!=0:\n",
    "                if  calorie- 100 >= 0:        \n",
    "                #if calories-100 is greater than 0 simply decrease the calorie and add the calories in 100 gm of food\n",
    "                    calorie-= 100\n",
    "                    totalCalories += caloriesCount[key]\n",
    "                else:                             # else add the fraction of calorie\n",
    "                    fraction = calorie/100\n",
    "                    totalCalories +=  caloriesCount[key]* fraction\n",
    "                    calorie = int(calorie - (caloriesCount[key] * fraction))\n",
    "                    break\n",
    "             \n",
    "    return totalCalories   #returing the total calorie\n",
    "# The caloriesCalculator function is designed to compute the total calories consumed by a child based on the quantities\n",
    "# of different types of food they have eaten. The function takes a dictionary called calories as input,\n",
    "# where each key represents a food type (such as \"Milk,\" \"Vegetables,\" \"Meat,\" etc.), and \n",
    "# the corresponding value indicates the amount of that food consumed. \n",
    "# The function begins by initializing a variable totalCalories to keep track of the overall calorie count.\n",
    "\n",
    "# It then iterates through each item in the calories dictionary using a loop, \n",
    "# where each item consists of a food type and the corresponding quantity consumed. \n",
    "# Inside the loop, the function calculates the total calories for each food type by \n",
    "# referring to a predefined caloriesCount dictionary. \n",
    "# This caloriesCount dictionary contains the calories contained in 100 grams of each food type.\n",
    "\n",
    "# The function employs a while loop to manage the calculations for each food type. \n",
    "# It checks if subtracting 100 calories from the current food's calorie count is possible without going below zero. \n",
    "# If so, it deducts 100 calories and adds the predetermined calories for that food type to the totalCalories.\n",
    "\n",
    "# If subtracting 100 calories would result in a negative value, the function calculates \n",
    "# the fraction of calories to be added based on the remaining amount. \n",
    "# It then adds the appropriate fraction of calories to totalCalories and updates \n",
    "# the remaining calorie count. The loop continues until the entire consumed amount has been processed.\n",
    "\n",
    "# After iterating through all food types, the function returns the totalCalories value, \n",
    "# which represents the cumulative calories consumed by the child, \n",
    "# considering both complete 100-gram portions and any remaining fractional portions of food. \n",
    "# This function helps provide an accurate estimate of the child's total calorie intake, \n",
    "# which is crucial for assessing their nutritional status and well-being.\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# nourishmentResult function to print the nourished status of child\n",
    "def nourishmentResult(childName,childAge,totalCalorie):\n",
    "    if childAge>=0 and childAge<2:      \n",
    "        #if childAge>=0 and childAge<2 and totalCalories<800- under-nourished else nourished\n",
    "        if totalCalories<800:\n",
    "            print(\"The daily calorie consumption of {0} is 800 and he (she) is taking {1},he or she required more calories  and he or she is  under-nourished.\".format(childName,totalCalories))\n",
    "        else:\n",
    "            print(\"The daily calorie consumption of {0} is 800 and he (she) is taking {1}, he or she is nourished.\".format(childName,totalCalories))\n",
    "    elif childAge>=2 and childAge<4:      \n",
    "            ##if childAge>=2 and childAge<4 and totalCalories<1400- under-nourished else nourished\n",
    "        if totalCalories<1400:\n",
    "            print(\"The daily calorie consumption of {0} is 1400 and he (she) is taking {1},he or she required more calories  and he or she is  under-nourished.\".format(childName,totalCalories))\n",
    "        else:\n",
    "            print(\"The daily calorie consumption of {0} is 1400 and he (she) is taking {1}, he or she is nourished.\".format(childName,totalCalories))\n",
    "    elif childAge>=4 and childAge<8:\n",
    "            ##if childAge>=4 and childAge<8 and totalCalories<1800- under-nourished else nourished\n",
    "        if totalCalories<1800:\n",
    "            print(\"The daily calorie consumption of {0} is 1800 and he (she) is taking {1},he or she required more calories  and he or she is  under-nourished.\".format(childName,totalCalories))\n",
    "        else:\n",
    "            print(\"The daily calorie consumption of {0} is 1800 and he (she) is taking {1}, he or she is nourished.\".format(childName,totalCalories))\n",
    "    else:\n",
    "        print(\"He(or She) is not Child!\")\n",
    "                                                                \n",
    "# The nourishmentResult function is aimed at assessing the nourishment status of a child based on their \n",
    "# age and total calorie consumption. This function takes three parameters as inputs: childName (the name of the child), \n",
    "# childAge (the age of the child), and totalCalorie (the total number of calories consumed by the child in a day).\n",
    "\n",
    "# The function starts by evaluating the age of the child in different age ranges: 0-2 years, 2-4 years, and 4-8 years. \n",
    "# Within each age range, it assesses whether the child's total calorie consumption is sufficient for adequate nourishment.\n",
    "\n",
    "# For children aged 0 to 2 years, the function checks if the total calories consumed (totalCalorie) \n",
    "# are less than 800. If the condition is met, it prints a message indicating that the child's daily\n",
    "# calorie consumption should ideally be 800, and the child is taking less than that amount. \n",
    "# This suggests that the child requires more calories for proper nourishment, leading to a classification of \n",
    "# \"under-nourished.\" If the total calories are greater than or equal to 800, the function concludes that \n",
    "#  the child is \"nourished.\"\n",
    "\n",
    "# Similarly, for children aged 2 to 4 years, the function compares the total calories consumed to a value of 1400. \n",
    "# If the calories are below this threshold, the child is considered \"under-nourished.\" \n",
    "# If the calories meet or exceed 1400, the child is considered \"nourished.\"\n",
    "\n",
    "# For children aged 4 to 8 years, the function uses a threshold of 1800 calories to make the same assessment \n",
    "# regarding nourishment status.\n",
    "\n",
    "# If the age of the child does not fall within any of these predefined ranges (0-2 years, 2-4 years, or 4-8 years), \n",
    "# the function prints a message stating that the given age does not correspond to that of a child.\n",
    "\n",
    "# In summary, the nourishmentResult function provides insights into the nourishment status of a child based on \n",
    "# their age and total calorie consumption. It helps in determining whether the child is consuming an adequate \n",
    "# amount of calories for their age group, thus contributing to an assessment of their nutritional well-being.\n",
    "#\n",
    "        \n",
    "        \n",
    "#Main Function\n",
    "#Taking details of child\n",
    "print(\"WELCOME TO CHILD NUTRITION CALCULATOR\")\n",
    "childName=input(\"Name:\")                         \n",
    "childAge=int(input(\"Age:\"))\n",
    "childHeight=float(input(\"Height(inches):\"))\n",
    "childWeight=float(input(\"Weight(lb):\"))\n",
    "\n",
    "print(\"\")\n",
    "\n",
    "#Taking daily calorie consumption of child\n",
    "print(\"Calorie Consumption of child\")\n",
    "calories={}\n",
    "calories[\"Milk\"]=int(input(\"Milk:\"))\n",
    "calories[\"Vegetables\"]=int(input(\"Vegetables:\"))\n",
    "calories[\"Meat\"]=int(input(\"Meat:\"))\n",
    "calories[\"Lentils\"]=int(input(\"Lentils:\"))\n",
    "calories[\"Egg\"]=int(input(\"Egg:\"))\n",
    "calories[\"Rice\"]=int(input(\"Rice:\"))\n",
    "\n",
    "print(\"\")\n",
    "\n",
    "#calculating bmi using bmi formula\n",
    "# The multiplication by 703 is used in the calculation of BMI when the height\n",
    "# is measured in inches and weight is measured in pounds. \n",
    "# The standard BMI formula is calculated using the metric system (weight in kilograms and height in meters squared). \n",
    "bmi = (childWeight/(childHeight**2))*703\n",
    "bmiTwoDecimal= round(bmi, 2)    #rounding bmi to 2 decimal places\n",
    "\n",
    "#passing child name and bmi to bmiResult to print the BMI Categories\n",
    "bmiResult(childName,bmiTwoDecimal)   \n",
    "\n",
    "print(\"\")\n",
    "\n",
    "#Passing calories dictionary to caloriesCalculator to calculate total calories consumed by child\n",
    "totalCalories=caloriesCalculator(calories)  \n",
    "totalCaloriesTwoDecimal= round(totalCalories, 2)   #rounding total calories to 2 decimal places\n",
    "\n",
    "#passing child name, age and total calories consumed to nourishmentResult to print the nourished status of child\n",
    "nourishmentResult(childName,childAge,totalCaloriesTwoDecimal)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c11e39ce",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
